# Generated by Django 4.2.7 on 2023-12-04 23:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=255)),
                ('watered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('gardener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garden', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
