# Generated by Django 5.0 on 2023-12-05 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0002_alter_garden_name'),
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='garden',
            name='name',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='garden',
            name='watered',
        ),
        migrations.CreateModel(
            name='Garden_plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('garden', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='favorites_app.garden')),
                ('plant', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plants', to='plant_app.plant')),
            ],
        ),
    ]
