# Generated by Django 5.0 on 2023-12-05 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0003_remove_garden_name_remove_garden_notes_and_more'),
        ('plant_app', '0003_alter_plant_cycle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_plants',
            name='garden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='garden_plant', to='favorites_app.garden'),
        ),
        migrations.AlterField(
            model_name='garden_plants',
            name='plant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='plant_app.plant'),
        ),
    ]
