# Generated by Django 5.0 on 2023-12-05 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites_app', '0004_alter_garden_plants_garden_alter_garden_plants_plant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='garden_plants',
            name='garden',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='garden_plants', to='favorites_app.garden'),
        ),
    ]
