# Generated by Django 5.0 on 2023-12-07 22:48

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0006_alter_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='myplants',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
