# Generated by Django 5.0 on 2023-12-05 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(default=None, max_length=255)),
                ('scientific_name', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('cycle', models.CharField(blank=True, default=None, max_length=255)),
                ('watering', models.CharField(blank=True, default=None, max_length=255, null=True)),
                ('thumbnail_url', models.CharField(default=None, null=True)),
                ('watered', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
