# Generated by Django 5.0 on 2023-12-05 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='thumbnail_url',
            field=models.CharField(blank=True, default=None, null=True),
        ),
    ]
