# Generated by Django 5.0 on 2023-12-05 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0002_alter_plant_thumbnail_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='cycle',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
