# Generated by Django 5.0 on 2023-12-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0003_alter_plant_cycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='sunlight',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
