# Generated by Django 5.0 on 2023-12-08 21:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0004_plant_sunlight'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 12, 8, 21, 29, 55, 488165, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
