# Generated by Django 4.2.7 on 2023-12-11 20:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0007_alter_plant_last_watered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='last_watered',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
