# Generated by Django 5.0 on 2023-12-14 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plant_app', '0008_alter_plant_last_watered'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='last_fertilized',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
